CREATE TABLE Songs (
  SongID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Lyrics TEXT NOT NULL,
  GuitarTabs TEXT,
  Minutes INTEGER,
  Seconds INTEGER,
  ReleaseDate VARCHAR(4),
  YoutubeLink VARCHAR(2048),
  SpotifyLink VARCHAR(2048),
  UNIQUE(Title, Lyrics));
CREATE TABLE Notes (
  NoteID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Value VARCHAR(2) NOT NULL UNIQUE);
CREATE TABLE ScaleInfo (
  ScaleInfoID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name VARCHAR(20) NOT NULL UNIQUE,
  IsMinor BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE Scales (
  ScaleID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  ScaleInfoID INTEGER NOT NULL,
  NoteID INTEGER NOT NULL,
  UNIQUE(ScaleInfoID, NoteID),
  FOREIGN KEY(ScaleInfoID) REFERENCES ScaleInfo(ScaleInfoID),
  FOREIGN KEY(NoteID) REFERENCES Notes(NoteID));
CREATE TABLE SongsScales (
  SongID INTEGER NOT NULL,
  ScaleID INTEGER NOT NULL,
  PRIMARY KEY (SongID, ScaleID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(ScaleID) REFERENCES Scales(ScaleID));
CREATE TABLE Tempos (
  TempoID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Value VARCHAR(5) NOT NULL UNIQUE);
CREATE TABLE Rhythms (
  RhythmID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Name VARCHAR(30) NOT NULL,
  TempoID INTEGER NOT NULL,
  UNIQUE(Name, TempoID),
  FOREIGN KEY(TempoID) REFERENCES Tempos(TempoID));
CREATE TABLE SongsRhythms (
  SongID INTEGER NOT NULL,
  RhythmID INTEGER NOT NULL,
  PRIMARY KEY (SongID, RhythmID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(RhythmID) REFERENCES Rhythms(RhythmID));
CREATE TABLE Artists (
  ArtistID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  FirstName VARCHAR(40) NOT NULL,
  LastName VARCHAR(40) NOT NULL,
  Nickname VARCHAR(40),
  Image VARCHAR(100),
  UNIQUE(FirstName, LastName));
CREATE TABLE SongsSingers (
  SongID INTEGER NOT NULL,
  SingerID INTEGER NOT NULL,
  PRIMARY KEY (SongID, SingerID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(SingerID) REFERENCES Artists(ArtistID));
CREATE TABLE SongsComposers (
  SongID INTEGER NOT NULL,
  ComposerID INTEGER NOT NULL,
  PRIMARY KEY (SongID, ComposerID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(ComposerID) REFERENCES Artists(ArtistID));
CREATE TABLE SongsAuthors (
  SongID INTEGER NOT NULL,
  AuthorID INTEGER NOT NULL,
  PRIMARY KEY (SongID, AuthorID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(AuthorID) REFERENCES Artists(ArtistID));
CREATE TABLE Tags (
  TagID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  Label VARCHAR(100) NOT NULL,
  UNIQUE(Label));
CREATE TABLE SongsTags (
  SongID INTEGER NOT NULL,
  TagID INTEGER NOT NULL,
  PRIMARY KEY (SongID, TagID),
  FOREIGN KEY(SongID) REFERENCES Songs(SongID),
  FOREIGN KEY(TagID) REFERENCES Tags(TagID));
